---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: centos
  become: true

  roles:
    - common

- name: configure and deploy the webservers and application code
#  hosts: webservers
  hosts:  tag_node_type_app  
  remote_user: centos
  become: true

  roles:
    - web

- name: deploy MySQL and configure the databases
#  hosts: dbservers
  hosts: tag_node_type_db
  remote_user: centos
  become: true

  roles:
    - db
